### PR TITLE
Fix production stall and clean up atomic usage

### LINKED ISSUE #81: [BUG]: Erroneously stops producing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Sometimes the block producer believes it has fallen outside of the production threshold when it has not.

It would appear that there is a conversion of a signed int to unsigned int that results in a bogus value of time delta.

### Expected behavior

It should not stop producing unless it actually feels out of the production threshold.

### Steps to reproduce

_No response_

### Environment

```markdown
- OS:
```

### Anything else?

```console
2021-11-23 14:49:38.579468 (block_producer.Koinos) [block_producer.cpp:296] <info>: Fell outside 1800s of head block time, stopping production
2021-11-23 14:49:38.579636 (block_producer.Koinos) [block_producer.cpp:297] <info>: Now: 1637707778579, Block Time: 1637707781307, Time Delta: 18446744073709548888
```

### PR DESCRIPTION
**Pull request by mvandeberg**
Closes #81

### CODE REVIEW

File: libraries/block_production/block_producer.cpp [hunk 1]
```diff
@@ -267,8 +267,13 @@ uint64_t block_producer::now()
...
 void block_producer::on_block_accept( const protocol::block& b )
 {
-   if ( b.header().timestamp() > _last_block_time )
-      _last_block_time = b.header().timestamp();
+   auto last_block_time = _last_block_time.load();
+
+   if ( b.header().timestamp() > last_block_time )
+   {
+      last_block_time = b.header().timestamp();
+      _last_block_time = last_block_time;
```
Comment (sgerbino) [inline libraries/block_production/block_producer.cpp:275]: Should we assert here to prevent an overflow in 240 years?

**Review by sgerbino — APPROVED** [review]

**Review by sgerbino — APPROVED** [review]
